Host=novatalks-dev.k3s.test.novait.com.ua
NodeRed=novatalks-dev.k3s.test.novait.com.ua
CataloguePath=C:/Warehouse/Repositories/
RepDataPath=novatalks.tests/automation/jmeter/
ApiAccessToken=CLcJoUWU7GGxeVMc7ZzX6WtY
accountId=1
inboxId=1
teamId=4
TelegramID=1
DatabaseURL=jdbc:postgresql://192.168.123.131:65432/test-novatalks-dev-novatalks
DatabaseUser=test-novatalks-dev-novatalks-svc
DatabasePassword=password
ConcurrentAgentNumber=3
AgentRampUp=60
ConcurrentClientNumber=4
ClientRampUp=60
InfluxdbUrl=http://127.0.0.1:8087
dataInterval=5
spreadInterval=6
BuildTag=test3
CompareBuildTag=test2
kubeConfigPath=C:/Warehouse/Repositories/novatalks.tests/automation/jmeter/resources/
kubeConfigYaml=dev-01-test.yaml
kubeDomainName=rancher.novait.local
kubeServerIP=192.168.190.7
kubeApiAuthToken=token-2rfvf:nrdz7klzkdkkp4gnjm9ntpqvpc7d98f5lth6cnmqv6984v6zk4bmqv
namespace=novatalks-dev
promDomainName=prometheus.k3s.test.novait.local
promServerIP=192.168.123.130
promStep=15